### PR TITLE
RELATED: RAIL-341 add docker .config

### PR DESCRIPTION
**Pull request by langhammerp**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/5/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-el7/352/ : SUCCESS in 1m 01s

**Comment by langhammerp** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/9/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-el7/357/ : SUCCESS in 1m 26s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/1/ : SUCCESS in 3m 30s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-merge-compliance-check/20/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-el7/358/ : SUCCESS in 1m 10s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/2/ : SUCCESS in 2m 02s (non-voting)

**Pull request merged**
