### PR TITLE
RELATED: RAIL-655 Conversion of vis. obj. with identifiers

### PR DESCRIPTION
**Pull request by vaclavbohac**
* [ ] Solve backend icompatibility

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/146/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/157/ : SUCCESS in 51s

**Comment by vaclavbohac** [comment]
`6.0.0-vaclavbohac-afm-vo-conversion-2018-02-23T14-48-24-866Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/157/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/172/ : SUCCESS in 58s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-merge-compliance-check/43/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/173/ : SUCCESS in 28s

**Pull request merged**
