### PR TITLE
RELATED: RAIL-657 Updated gooddata-js

### PR DESCRIPTION
**Pull request by vojty**
`@gooddata/data-layer@6.0.0-vojty-factory-sdk-2018-03-01T09-51-43-781Z`

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/138/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/147/ : SUCCESS in 50s

**Comment by zbycz** [comment]
`@gooddata/data-layer@6.0.0-pavelzgdc-vojty-factory-sdk-2018-02-23T12-20-10-100Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/145/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/156/ : SUCCESS in 1m 04s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/150/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/162/ : SUCCESS in 48s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/151/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/163/ : SUCCESS in 49s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-merge-compliance-check/40/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/164/ : SUCCESS in 25s

**Pull request merged**
