### PR TITLE
RELATED: RAIL-582 Prevent date filter duplication

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
`@gooddata/data-layer@5.0.0-vaclavbohac-date-filter-dup-2018-01-08T16-19-40-262Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/73/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/74/ : SUCCESS in 1m 03s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/75/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/76/ : SUCCESS in 1m 00s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-merge-compliance-check/29/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/78/ : SUCCESS in 1m 06s

**Pull request merged**
