### PR TITLE
RELATED: RAIL-657 Update gooddata-js 

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
`6.0.0-vaclavbohac-revert-factory-sdk-2018-03-06T15-05-09-028Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/154/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/168/ : SUCCESS in 59s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-opensource-repository-check/155/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/169/ : SUCCESS in 55s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-data-layer-merge-compliance-check/42/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-data-layer-unit-tests-zuul-docker-el7/170/ : SUCCESS in 45s

**Pull request merged**
